name: Create and Review PR

on:
  push:
    branches:
      - main

jobs:
  create_pr:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Install pnpm
        run: |
          npm install -g pnpm
          pnpm config set store-dir ~/.pnpm-store

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Update version in package.json
        if: github.ref_type == 'branch'
        run: |
          jq --arg build "$GITHUB_RUN_NUMBER" --arg commit "${GITHUB_SHA::8}" \
          '.version = .version + "-dev." + $build + "+" + $commit' package.json > package.json.tmp
          mv package.json.tmp package.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update version to ${{ github.sha }}
          branch: update-version
          title: "Automated version update"
          body: "This PR was created automatically by the release workflow."

      - name: Request Reviewers
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pullRequests } = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: 'update-version',
              state: 'open'
            });

            if (pullRequests.length > 0) {
              const prNumber = pullRequests[0].number;
              await github.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber,
                reviewers: ['bo-like-chicken']
              });
            } else {
              throw new Error("No open pull request found for branch 'update-version'");
            }
